name: nyxx
version: 1.0.0
description: A Discord library for Dart. For of hackzzila's nyx.
authors:
- Szymon Uglis <szymon.uglis@tuta.io>
- Hackzzila <admin@hackzzila.com>
homepage: https://github.com/l7ssha/nyxx
documentation: https://github.com/l7ssha/nyxx
environment:
  sdk: '>=2.0.0-dev.63.0 <3.0.0'
dependencies:
  http: ^0.11.3+17
  logging: "^0.11.3+2"
  yaml: "^2.1.15"
dev_dependencies:
  dart_style:
