name: discord
version: 0.12.0
description: A Discord library for Dart
author: Hackzzila <admin@hackzzila.com>
homepage: https://hackzzila.github.io/Discord-Dart/
dependencies:
  http: ">=0.11.3+9 <0.12.0"
  events: ">=0.1.2+1 <0.2.0"
  http_parser: ">=3.0.2 <4.0.0"
dev_dependencies:
  dart_style:
