name: discord
version: 0.14.2
description: A Discord library for Dart
author: Hackzzila <admin@hackzzila.com>
homepage: https://hackzzila.github.io/Discord-Dart/
dependencies:
  http: ">=0.11.3+9 <0.12.0"
  http_utils: ">=1.4.0 <2.0.0"
  intl: ">=0.14.0 <0.15.0"
  http_parser: ">=3.0.2 <4.0.0"
  args: ">=0.13.5 <0.14.0"
dev_dependencies:
  dart_style:
