name: discord
version: 0.15.0
description: A Discord library for Dart
author: Hackzzila <admin@hackzzila.com>
homepage: https://hackzzila.github.io/Discord-Dart/
dependencies:
  intl: ">=0.14.0 <0.15.0"
  http_parser: ">=3.0.2 <4.0.0"
  args: ">=0.13.5 <0.14.0"
  w_transport: ">=2.9.4 <3.0.0"
dev_dependencies:
  dart_style:
