name: nyxx
version: 0.21.3
description: A Discord library for Dart. For of hackzzila's nyx.
authors:
- Szymon 'l7ssha' Uglis <szymon.uglis@tuta.io>
- Hackzzila <admin@hackzzila.com>
homepage: https://github.com/l7ssha/nyxx
documentation: https://github.com/l7ssha/nyxx
environment:
  sdk: '>=1.23.0 <2.0.0'
dependencies:
  http_parser: ">=3.0.0 <4.0.0"
  w_transport: ">=3.0.0 <4.0.0"
dev_dependencies:
  dart_style:
