name: nyxx.extensions
version: 1.0.0
description: Extensions for Nyxx library
authors:
- Szymon Uglis <szymon.uglis@tuta.io>
- Zach Vacura <admin@hackzzila.com>
homepage: https://github.com/l7ssha/nyxx
repository: https://github.com/l7ssha/nyxx
documentation: https://github.com/l7ssha/nyxx/wiki
issue_tracker: https://github.com/l7ssha/nyxx/issue

environment:
  sdk: '>=2.9.0-10.0.dev <3.0.0'

dependencies:
  nyxx: "^1.0.0"

dependency_overrides:
  nyxx:
    path: "../nyxx"

dev_dependencies:
  dart_style:
  analyzer:
