name: nyxx_extensions
version: 2.0.0-rc.1
description: Extensions for Nyxx library
homepage: https://github.com/l7ssha/nyxx
repository: https://github.com/l7ssha/nyxx
documentation: https://github.com/l7ssha/nyxx/wiki
issue_tracker: https://github.com/l7ssha/nyxx/issue

environment:
  sdk: '>=2.12.0 <2.13.0'

dependencies:
  http: "^0.13.1"
  nyxx: "^2.0.0-rc.1"