name: nyxx_interactions
version: 2.0.0-rc.4
description: Interactions for Nyxx library
homepage: https://github.com/l7ssha/nyxx
repository: https://github.com/l7ssha/nyxx
documentation: https://github.com/l7ssha/nyxx/wiki
issue_tracker: https://github.com/l7ssha/nyxx/issue

environment:
  sdk: '>=2.12.0 <2.13.0'

dependencies:
  logging: "^1.0.1"
  nyxx: "2.0.0-rc.3"
