name: deploy dev docs

on:
  push:
    branches:
      - dev

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: [ "nyxx", "nyxx_commander", "nyxx_extensions", "nyxx_interactions", "nyxx_lavalink" ]

    steps:
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.pub_cache
          key: ${{ runner.os }}

      - name: Setup Dart Action
        uses: cedx/setup-dart@v2.3.0
        with:
         release-channel: stable

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install dependencies
        working-directory: ./${{ matrix.package }}
        run: dart pub get

      - name: Generate docs
        working-directory: ./${{ matrix.package }}
        run: dartdoc

      - name: Deploy nyxx dev docs
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_SERVER_KEY }}
          ARGS: "-rltDzvO"
          SOURCE: "${{ matrix.package }}/doc/api/"
          REMOTE_HOST: ${{ secrets.DEPLOY_REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.DEPLOY_REMOTE_USER }}
          TARGET: "${{ secrets.DEPLOY_REMOTE_TARGET }}/dartdocs/${{ matrix.package }}/"
