name: integration tests

on:
  push:
    branches:
      - dev

jobs:
  test-nyxx:
    name: Test main nyxx package
    runs-on: ubuntu-latest
    env:
      TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
    steps:
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.pub_cache
          key: ${{ runner.os }}

      - name: Setup Dart Action
        uses: dart-lang/setup-dart@v1

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install dependencies
        run: dart pub get

      - name: Analyze project source
        run: dart analyze

      - name: Compile tests
        working-directory: ./test
        run: dart2native travis.dart

      - name: Run tests
        working-directory: ./test
        run: ./travis.exe
