name: publish

on:
  push:
    branches:
      - main

jobs:
  nyxx_publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check if version in constants.dart is correct'
        run: |
          apt-get update -y
          apt install pcregrep -y
          (if [ $(pcregrep -o1 'static const String version = "(.+)";' < lib/src/internal/constants.dart) != $(pcregrep -o1 'version: (.+)$' < pubspec.yaml) ]; then exit 1; fi)

      - uses: actions/checkout@v2
      - name: 'publish nyxx package to pub.dev'
        id: publish
        uses: k-paxian/dart-package-publisher@master
        with:
          skipTests: true
          force: true
          suppressBuildRunner: true
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}

      - name: 'Commit release tag'
        if: steps.publish.outputs.success
        uses: hole19/git-tag-action@master
        env:
          TAG: ${{steps.publish.outputs.package}}-${{steps.publish.outputs.localVersion}}
          GITHUB_TOKEN: ${{ secrets.TAG_RELEASE_TOKEN }}
