name: Tests

on: [push, pull_request]

jobs:
  test-nyxx:
    name: Test main nyxx package
    runs-on: ubuntu-latest
    env:
      TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
    steps:
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.pub_cache
          key: ${{ runner.os }}

      - name: Setup Dart Action
        uses: cedx/setup-dart@v2.3.0
        with:
         release-channel: stable

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install dependencies
        working-directory: ./nyxx
        run: dart pub get

      - name: Analyze project source
        working-directory: ./nyxx
        run: dart analyze

      - name: Unit tests
        working-directory: ./nyxx
        run: dart test test/unit.dart

      - name: Compile tests
        working-directory: ./nyxx/test
        run: dart2native travis.dart
        if: github.event_name != 'pull_request'

      - name: Run tests
        working-directory: ./nyxx/test
        run: ./travis.exe
        if: github.event_name != 'pull_request'

      - name: Generate docs
        working-directory: ./nyxx
        run: dartdoc

      - name: Deploy nyxx dev docs
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltDzvO"
          SOURCE: "nyxx/doc/api/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "${{ secrets.REMOTE_TARGET }}/nyxx/"

  test-commander:
    name: Tests commander package
    needs: [test-nyxx]
    runs-on: ubuntu-latest
    env:
      TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
    steps:
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.pub_cache
          key: ${{ runner.os }}

      - name: Setup Dart Action
        uses: cedx/setup-dart@v2.3.0
        with:
         release-channel: stable

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install dependencies
        working-directory: ./nyxx.commander
        run: dart pub get

      - name: Analyze project source
        working-directory: ./nyxx.commander
        run: dart analyze

      - name: Compile tests
        working-directory: ./nyxx.commander/test
        run: dart2native commander-test.dart
        if: github.event_name != 'pull_request'

      - name: Run tests
        working-directory: ./nyxx.commander/test
        run: ./commander-test.exe
        if: github.event_name != 'pull_request'

      - name: Generate docs
        working-directory: ./nyxx.commander
        run: dartdoc

      - name: Deploy nyxx.commander dev docs
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltDzvO"
          SOURCE: "nyxx.commander/doc/api/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "${{ secrets.REMOTE_TARGET }}/nyxx.commander/"

  test-extensions:
    name: Tests extensions package
    needs: [test-commander]
    runs-on: ubuntu-latest
    env:
      TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
    steps:
     - name: Cache
       uses: actions/cache@v2
       with:
        path: ~/.pub_cache
        key: ${{ runner.os }}

     - name: Setup Dart Action
       uses: cedx/setup-dart@v2.3.0
       with:
        release-channel: stable

     - name: Checkout
       uses: actions/checkout@v2.3.4

     - name: Install dependencies
       working-directory: ./nyxx.extensions
       run: dart pub get

     - name: Analyze project source
       working-directory: ./nyxx.extensions
       run: dart analyze

     - name: Compile tests
       working-directory: ./nyxx.extensions/test
       run: dart2native extensions-tests.dart
       if: github.event_name != 'pull_request'

     - name: Run tests
       working-directory: ./nyxx.extensions/test
       run: ./extensions-tests.exe
       if: github.event_name != 'pull_request'

     - name: Generate docs
       working-directory: ./nyxx.extensions
       run: dartdoc

     - name: Deploy nyxx.extensions dev docs
       uses: easingthemes/ssh-deploy@v2.1.5
       env:
         SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
         ARGS: "-rltDzvO"
         SOURCE: "nyxx.extensions/doc/api/"
         REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
         REMOTE_USER: ${{ secrets.REMOTE_USER }}
         TARGET: "${{ secrets.REMOTE_TARGET }}/nyxx.extensions/"

  test-interactions:
    name: Tests interactions package
    needs: [ test-extensions ]
    runs-on: ubuntu-latest
    env:
      TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
    steps:
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.pub_cache
          key: ${{ runner.os }}

      - name: Setup Dart Action
        uses: cedx/setup-dart@v2.3.0
        with:
          release-channel: stable

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install dependencies
        working-directory: ./nyxx.interactions
        run: dart pub get

      - name: Analyze project source
        working-directory: ./nyxx.interactions
        run: dart analyze

      - name: Generate docs
        working-directory: ./nyxx.interactions
        run: dartdoc

      - name: Deploy nyxx.interactions dev docs
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltDzvO"
          SOURCE: "nyxx.interactions/doc/api/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "${{ secrets.REMOTE_TARGET }}/nyxx.interactions/"
