name: unit tests

on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  test-nyxx:
    name: Test main nyxx package
    runs-on: ubuntu-latest
    env:
      TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
    steps:
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.pub_cache
          key: ${{ runner.os }}

      - name: Setup Dart Action
        uses: cedx/setup-dart@v2.3.0
        with:
         release-channel: stable

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install dependencies
        working-directory: ./nyxx
        run: dart pub get

      - name: Analyze project source
        working-directory: ./nyxx
        run: dart analyze

      - name: Unit tests
        working-directory: ./nyxx
        run: dart test test/unit.dart

  analyze-subpackages:
    needs: [ test-nyxx ]
    runs-on: ubuntu-latest
    env:
      TEST_TOKEN: ${{ secrets.TEST_TOKEN }}

    strategy:
      matrix:
        package: [ "nyxx_commander", "nyxx_lavalink" ]
    steps:
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.pub_cache
          key: ${{ runner.os }}

      - name: Setup Dart Action
        uses: cedx/setup-dart@v2.3.0
        with:
          release-channel: stable

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install dependencies
        working-directory: ./${{ matrix.package }}
        run: dart pub get

      - name: Analyze project source
        working-directory: ./${{ matrix.package }}
        run: dart analyze

  test-subpackages:
    needs: [ test-nyxx ]
    runs-on: ubuntu-latest
    env:
      TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
    strategy:
      matrix:
        adapter: ["nyxx_extensions", "nyxx_interactions" ]
    steps:
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.pub_cache
          key: ${{ runner.os }}

      - name: Setup Dart Action
        uses: cedx/setup-dart@v2.3.0
        with:
          release-channel: stable

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install dependencies
        working-directory: ./${{ matrix.package }}
        run: dart pub get

      - name: Analyze project source
        working-directory: ../${{ matrix.package }}
        run: dart analyze

      - name: Unit tests
        working-directory: ./${{ matrix.package }}
        run: dart test test/extensions-tests.dart
